providers:
  # Mock Provider - 用于测试
  mock:
    provider: "mock"
    model: "mock-model"
    api_key: "mock-api-key"
    api_base: "https://mock.api.com"
    max_tokens: 4000
    temperature: 0.7
    timeout: 30
    max_retries: 3

  # 智谱AI Provider - 推荐使用
  zhipu:
    provider: "zhipu"
    model: "glm-4.5-air"
    api_key: "${ZHIPU_API_KEY}"
    api_base: "https://open.bigmodel.cn/api/paas/v4/"
    max_tokens: 4000
    temperature: 0.3
    timeout: 60
    max_retries: 3

  # OpenAI Provider
  openai:
    provider: "openai"
    model: "gpt-4"
    api_key: "${OPENAI_API_KEY}"
    api_base: "${OPENAI_BASE_URL:https://api.openai.com/v1}"
    max_tokens: 4000
    temperature: 0.3
    timeout: 30
    max_retries: 3

  # Anthropic Provider
  anthropic:
    provider: "anthropic"
    model: "claude-3-sonnet-20240229"
    api_key: "${ANTHROPIC_API_KEY}"
    api_base: "${ANTHROPIC_BASE_URL:https://api.anthropic.com}"
    max_tokens: 4000
    temperature: 0.3
    timeout: 30
    max_retries: 3