providers:
  mock:
    provider: "mock"
    model: "mock-model"
    api_key: "mock-api-key"
    api_base: "https://mock.api.com"
    max_tokens: 4000
    temperature: 0.7
    timeout: 30
    max_retries: 3