# 用户配置文件
# 配置真实API密钥来使用深度分析功能

# 用户API密钥配置
llm:
  # 选择默认的LLM提供商
  default_provider: "zhipu"  # 可选: zhipu, openai, anthropic

  # 智谱AI配置 (推荐，国内访问稳定)
  zhipu:
    api_key: "${ZHIPU_API_KEY}"  # 建议使用环境变量
    model: "glm-4.5"
    base_url: "https://open.bigmodel.cn/api/paas/v4/"
    max_tokens: 4000
    temperature: 0.3
    timeout: 30

  # OpenAI配置 (需要代理访问)
  openai:
    api_key: "${OPENAI_API_KEY}"  # 建议使用环境变量
    model: "gpt-4"
    base_url: "${OPENAI_BASE_URL:https://api.openai.com/v1}"
    max_tokens: 4000
    temperature: 0.3
    timeout: 30

  # Anthropic配置 (需要代理访问)
  anthropic:
    api_key: "${ANTHROPIC_API_KEY}"  # 建议使用环境变量
    model: "claude-3-sonnet-20240229"
    base_url: "${ANTHROPIC_BASE_URL:https://api.anthropic.com}"
    max_tokens: 4000
    temperature: 0.3
    timeout: 30

# 用户自定义静态分析配置
static_analysis:
  enabled_tools:
    - "ast"
    - "pylint"
    - "flake8"
    - "bandit"

  # Pylint自定义配置
  pylint:
    disable_codes: ["C0114", "C0115", "C0116", "R0903"]

  # Flake8自定义配置
  flake8:
    max_line_length: 100
    ignore_codes: ["E203", "W503", "E501"]

# 深度分析配置
deep_analysis:
  default_model: "glm-4.5"  # 深度分析默认模型
  max_file_size: 100000  # 最大文件大小 (100KB)
  temperature: 0.3
  max_tokens: 4000

# 用户Web界面配置
web:
  host: "0.0.0.0"  # 允许外部访问
  port: 8080
  debug: false

# 用户CLI配置
cli:
  output_format: "rich"
  colored_output: true