# AIDefectDetector 生产环境配置模板
# 适用于生产部署和稳定运行

llm:
  # 生产环境优先使用智谱AI（国内稳定）
  default_provider: "zhipu"

  # 启用回退机制
  fallback_providers: ["openai", "anthropic", "mock"]
  enable_fallback: true
  max_retry_attempts: 3

  # 智谱AI生产配置
  zhipu:
    provider: "zhipu"
    model: "glm-4.5"
    api_key: "${ZHIPU_API_KEY}"
    api_base: "https://open.bigmodel.cn/api/paas/v4/"
    max_tokens: 8000           # 生产环境增加token限制
    temperature: 0.2           # 生产环境降低创造性，提高准确性
    timeout: 60                # 增加超时时间
    max_retries: 5             # 增加重试次数
    retry_delay: 2.0

  # OpenAI备用配置
  openai:
    provider: "openai"
    model: "gpt-4-turbo"
    api_key: "${OPENAI_API_KEY}"
    api_base: "${OPENAI_BASE_URL:https://api.openai.com/v1}"
    max_tokens: 8000
    temperature: 0.2
    timeout: 60
    max_retries: 5
    retry_delay: 2.0
    organization: "${OPENAI_ORG_ID}"

  # Anthropic备用配置
  anthropic:
    provider: "anthropic"
    model: "claude-3-sonnet-20240229"
    api_key: "${ANTHROPIC_API_KEY}"
    api_base: "${ANTHROPIC_BASE_URL:https://api.anthropic.com}"
    max_tokens: 8000
    temperature: 0.2
    timeout: 60
    max_retries: 5
    retry_delay: 2.0

  # Mock紧急回退
  mock:
    provider: "mock"
    model: "mock-model"
    api_key: "mock-api-key"
    api_base: "https://mock.api.com"
    max_tokens: 4000
    temperature: 0.3
    timeout: 30

# 深度分析生产配置
deep_analysis:
  default_model: "glm-4.5"
  max_file_size: 200000        # 200KB，生产环境允许更大文件
  temperature: 0.2             # 生产环境追求准确性
  max_tokens: 6000             # 生产环境需要更详细的分析
  timeout: 120                 # 增加分析超时时间

# 不同分析类型的专用配置
analysis_types:
  security:
    temperature: 0.1           # 安全分析用最低温度
    max_tokens: 8000           # 需要详细的安全报告
    model: "glm-4.5"
    timeout: 180               # 安全分析需要更长时间

  performance:
    temperature: 0.2           # 性能分析用低温度
    max_tokens: 4000           # 重点关注性能问题
    model: "gpt-4-turbo"
    timeout: 120

  code_review:
    temperature: 0.1           # 代码审查用最低温度
    max_tokens: 6000           # 需要详细的审查报告
    model: "glm-4.5"
    timeout: 150

  architecture:
    temperature: 0.3           # 架构分析可以稍微灵活
    max_tokens: 8000           # 需要全面的架构分析
    model: "claude-3-sonnet-20240229"
    timeout: 200

# 日志配置
logging:
  level: "INFO"                # 生产环境使用INFO级别
  file_path: "logs/production.log"
  max_size: "100MB"
  backup_count: 10
  console_output: false        # 生产环境不输出到控制台
  structured: true             # 启用结构化日志

# 缓存配置
cache:
  backend: "redis"             # 生产环境使用Redis
  host: "${REDIS_HOST:localhost}"
  port: "${REDIS_PORT:6379}"
  password: "${REDIS_PASSWORD:}"
  ttl: 3600                    # 1小时缓存
  max_size: 10000

# 性能和限制配置
limits:
  max_concurrent_requests: 10   # 最大并发请求数
  rate_limit_per_minute: 60     # 每分钟请求限制
  max_file_size_mb: 10          # 最大文件大小10MB
  session_timeout: 1800         # 会话超时30分钟

# 监控配置
monitoring:
  enable_metrics: true         # 启用性能指标
  metrics_endpoint: "/metrics" # 指标端点
  health_check: true           # 启用健康检查
  alert_threshold: 0.8         # 告警阈值

# 安全配置
security:
  encrypt_api_keys: true       # 加密存储的API密钥
  mask_logs: true             # 日志中掩码敏感信息
  audit_requests: true        # 审计API请求