# AIDefectDetector 测试环境配置模板
# 适用于自动化测试和CI/CD

llm:
  # 测试环境强制使用Mock，避免API调用
  default_provider: "mock"

  mock:
    provider: "mock"
    model: "mock-model"
    api_key: "mock-api-key"
    api_base: "https://mock.api.com"
    max_tokens: 1000
    temperature: 0.5
    timeout: 5                 # 测试环境快速超时
    max_retries: 1

  # 可选：配置真实API用于集成测试
  # zhipu:
  #   provider: "zhipu"
  #   model: "glm-4.5"
  #   api_key: "${TEST_ZHIPU_API_KEY}"
  #   api_base: "https://open.bigmodel.cn/api/paas/v4/"
  #   max_tokens: 1000
  #   temperature: 0.3
  #   timeout: 10
  #   max_retries: 1

# 深度分析测试配置
deep_analysis:
  default_model: "mock-model"
  max_file_size: 10000         # 10KB，测试环境使用小文件
  temperature: 0.5
  max_tokens: 1000
  timeout: 30

# 日志配置
logging:
  level: "WARNING"             # 测试环境只显示警告和错误
  file_path: "/tmp/test.log"   # 临时日志文件
  max_size: "1MB"
  backup_count: 1
  console_output: false        # 测试时不输出到控制台

# 缓存配置
cache:
  backend: "memory"            # 测试环境使用内存缓存
  ttl: 60                      # 1分钟缓存
  max_size: 50                 # 限制缓存大小

# 测试特定配置
testing:
  mock_responses: true         # 启用模拟响应
  fast_mode: true             # 快速模式
  skip_network_calls: true    # 跳过网络调用
  deterministic: true         # 确定性输出

# 性能限制（测试环境）
limits:
  max_concurrent_requests: 2   # 限制并发数
  rate_limit_per_minute: 30    # 降低请求限制
  max_file_size_mb: 1          # 限制文件大小
  session_timeout: 300         # 短会话超时

# 分析配置
analysis:
  timeout: 30                  # 短超时时间
  parallel: false              # 测试时不并行
  verbose: false               # 测试时不显示详细输出
  mock_data: true             # 使用模拟数据